### ISSUE TITLE
Garbage collection of unused contents is needed

### ISSUE THREAD

**Issue by merks** [eclipse-simrel/simrel.tools#2]
This repository contains a large set of scripts, most of which are unused.  With so much garbage, it's difficult to maintain the parts that are actually still used.  In fact it's difficult to determine which parts are actually used.  To help with that, each job of https://ci.eclipse.org/simrel/ has its description augmented to include links to each script that it uses.  

This set of scripts appear to be garbage:

![image](https://github.com/eclipse-simrel/simrel.tools/assets/208716/80f43953-c1d8-46e0-b125-4dd409b628f3)

That leaves only this much more manageable subset:

![image](https://github.com/eclipse-simrel/simrel.tools/assets/208716/af1ad043-0398-4cf6-bea0-617a5cd7787d)

**Comment by fredg02** [comment]
Thanks for creating this issue. A clean-up is longer overdue.
